version: 1

formatters:
    default:
        format: "[%(asctime)s] %(levelname)s | %(name)s %(threadName)s >>> %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"

handlers:
    wsgi:
        class: logging.StreamHandler
        level: DEBUG
        formatter: default
        stream: ext://flask.logging.wsgi_errors_stream

loggers:
    development:
        level: DEBUG
        handlers: [wsgi]
        propagate: no

root:
    level: DEBUG
    handlers: [wsgi]
