version: 1

formatters:
    default:
        format: "[%(asctime)s] %(levelname)s | %(name)s %(threadName)s >>> %(message)s"
        datefmt: "%d-%m-%Y %H:%M:%S"

handlers:
    wsgi:
        class: logging.StreamHandler
        level: DEBUG
        formatter: default
        stream: ext://flask.logging.wsgi_errors_stream
    error_console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream: ext://sys.stderr

loggers:
    development:
        level: DEBUG
        handlers: [wsgi]
        propagate: False
    gunicorn.error:
        level: INFO
        handlers: [error_console]
        propagate: True

root:
    level: DEBUG
    handlers: [wsgi]
