version: 1

formatters:
    verbose:
        format: "VERBOSE [%(asctime)s] %(levelname)s | %(name)s %(threadName)s >>> %(message)s"
        datefmt: "%d-%m %H:%M:%S"
    simple:
        format: "SIMPLE [%(asctime)s] %(levelname)s | %(name)s %(message)s"
        datefmt: "%d-%m %H:%M:%S"

handlers:
    wsgi:
        class: logging.StreamHandler
        level: DEBUG
        formatter: verbose
        stream: ext://flask.logging.wsgi_errors_stream
    stderr:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stderr
    file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: app.log
        mode: a

loggers:
    development:
        level: DEBUG
        handlers: [wsgi]
        propagate: False
    production:
        level: DEBUG
        handlers: [stderr, file]
        propagate: True

root:
    level: DEBUG
    handlers: [wsgi]
