version: 1

formatters:
    werkzeug.format:
        format: "%(message)s"
    simple:
        format: "[%(asctime)s] %(levelname)s %(name)s - %(message)s"
        datefmt: "%d-%m %H:%M:%S"
    verbose:
        format: "[%(asctime)s] %(levelname)s %(name)s %(filename)s %(lineno)d - %(message)s"
        datefmt: "%d-%m %H:%M:%S"
      
handlers:
    werkzeug.console:
        class: logging.StreamHandler
        level: INFO
        formatter: werkzeug.format
        stream: ext://sys.stderr
    development.console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stderr
    production.console:
        class: logging.StreamHandler
        level: WARNING
        formatter: verbose
        stream: ext://sys.stderr
    production.file:
        class: logging.FileHandler
        level: WARNING
        formatter: verbose
        filename: app.log
        mode: a

loggers:
    werkzeug:
        level: INFO
        handlers: [werkzeug.console]
        propagate: False    
    development:
        level: DEBUG
        handlers: [development.console]
        propagate: False
    production:
        level: WARNING
        handlers: [production.console, production.file]
        propagate: True
